/**
 * App Redux Action Types
 */
export const ENABLE_APP_LOADING = 'ENABLE_APP_LOADING';
export const DISABLE_APP_LOADING = 'DISABLE_APP_LOADING';

// Auth user Actions
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_USER_SUCCESS = 'SET_AUTH_USER_SUCCESS';
export const SET_AUTH_USER_FAILURE = 'SET_AUTH_USER_FAILURE';
export const CLEAR_AUTH_USER = 'CLEAR_AUTH_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const SET_REQUEST_GLOBAL_LOADER = 'SET_REQUEST_GLOBAL_LOADER';

export const TICKETS = 'TICKETS';
export const TICKETS_SUCCESS = 'TICKETS_SUCCESS';
export const TICKETS_FAILURE = 'TICKETS_FAILURE';
